dataset:
  name: 'kitti_eigen'
  data_path: 'data/kitti/'
  data_path_eval: 'data/kitti/'
  gt_path: 'data/kitti/data_depth_annotated/'
  gt_path_eval: 'data/kitti/data_depth_annotated/'
  input_width: 1216
  input_height: 352
  min_depth: 1.0
  max_depth: 80.0

evaluation:
  do_kb_crop: true
  garg_crop: true
  eigen_crop: false
